from __future__ import annotations

from homeassistant.components.number import (
    NumberDeviceClass,
    NumberEntity,
)
from homeassistant.components.sensor import (
    SensorEntityDescription,
    SensorStateClass
)
from homeassistant.const import (
    EntityCategory,
    UnitOfElectricCurrent,
    UnitOfElectricPotential,
    UnitOfEnergy,
    UnitOfPower,
    UnitOfTemperature,
)
NUMBERS: dict[str, tuple[SensorEntityDescription, ...]] = {}

SENSORS: dict[str, tuple[SensorEntityDescription, ...]] = {
    # 家用电测设备
    "diance": (
        # 电流
        SensorEntityDescription(
            key="BRS_1_a_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_1_b_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_1_c_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_2_a_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_2_b_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_2_c_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_3_a_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_3_b_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_3_c_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_4_a_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_4_b_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_4_c_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_5_a_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_5_b_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_5_c_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_6_a_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_6_b_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        SensorEntityDescription(
            key="BRS_6_c_I",
            translation_key="current",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.CURRENT,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricCurrent.AMPERE,
        ),
        #电压
        SensorEntityDescription(
            key="BRS_Ua",
            translation_key="voltage",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.VOLTAGE,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfElectricPotential.VOLT,
        ),

        #功率
        SensorEntityDescription(
            key="BRS_1_a_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_1_b_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_1_c_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_2_a_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_2_b_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_2_c_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_3_a_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_3_b_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_3_c_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_4_a_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_4_b_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_4_c_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_5_a_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_5_b_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_5_c_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_6_a_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_6_b_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),
        SensorEntityDescription(
            key="BRS_6_c_P",
            translation_key="power",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.POWER,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfPower.KILO_WATT,
        ),

        #温度
        SensorEntityDescription(
            key="BRS_DEV1T",
            translation_key="temperature",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.TEMPERATURE,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        ),
        SensorEntityDescription(
            key="BRS_DEV2T",
            translation_key="temperature",
            state_class = SensorStateClass.MEASUREMENT,
            device_class=NumberDeviceClass.TEMPERATURE,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfTemperature.CELSIUS,
        ),

        #用电量
        SensorEntityDescription(
            key="BRS_1_a_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_1_b_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_1_c_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_2_a_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_2_b_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_2_c_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_3_a_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_3_b_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_3_c_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_4_a_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_4_b_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_4_c_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_5_a_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_5_b_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_5_c_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_6_a_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_6_b_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
        SensorEntityDescription(
            key="BRS_6_c_EP",
            translation_key="energy",
            state_class = SensorStateClass.TOTAL_INCREASING,
            device_class=NumberDeviceClass.ENERGY,
            entity_category=EntityCategory.DIAGNOSTIC,
            native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        ),
    ),


    


}